name: jfq
version: '1.1'
summary: jfq command line tool for JSONata
description: |
    Command line tool for JSONata parsing

grade: stable
confinement: strict

base: core18

architectures:
#  - build-on: amd64
  - build-on: armhf

parts:
  jfq:
    plugin: nodejs
    nodejs-package-manager: npm
    source-type: local
    source: .
    build-environment:
      - npm_config_unsafe_perm: 'true'

apps:
  jfq:
    command: jfq
